### ISSUE TITLE
The Jeilyfish package is malicious - did you mean "import jellyfish"?

### ISSUE THREAD

**Issue by bbrewington** [mohansuraj165/Capstone19#1]
https://www.zdnet.com/article/two-malicious-python-libraries-removed-from-pypi/

https://github.com/mohansuraj165/Capstone19/blob/54e9b0c174de100f90eae6a824deeccf93c18ce7/OSMPythonToolsHandler.py#L7

**Comment by wglasshusain** [comment]
See https://www.zdnet.com/article/two-malicious-python-libraries-removed-from-pypi/

**Comment by abhiTronix** [comment]
@mohansuraj165 https://github.com/dateutil/dateutil/issues/984#issue-530789681

**Comment by hugovk** [comment]
Please see PR https://github.com/mohansuraj165/Capstone19/pull/2.
